Готово
denis-shishki/java-filmorate pull request #4
Opened 2023-08-10 20:06 UTC by denis-shishki

2023-08-12 11:23 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film newFilm = Film.builder()
Хорошая практика использовать бильдер для создания объектов с многими полями.

2023-08-12 11:24 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new FilmNotFoundException("Фильма с данным идентификатором нет в базе");
Верное использование FilmNotFoundException для сообщения о том что не найдено.

2023-08-12 11:33 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        UserValidator.validate(user);
Можно сделать более "по спринговому":) и внедрить зависимость (для понимания и закрепления). 
В UserController добавляем поле UserValidator userValidator, а класс UserValidator  помечаем @Component.
В результате спринг сам создаст валидатор и подставит его в поле контроллера.

2023-08-12 11:37 UTC, VadimZharkov requested changes
Т.к. у обоих контроллеров одинаковая функциональнось по работе с сущностями модели (разница только в валидации), то можно выделить ее в базовый контроллер. Сущности модели тоже имеют общую часть - идентификатор, и можно сделать базовый класс, назвать например Entity.
В итоге базовый контроллер мог бы иметь такое определение

public abstract class Controller<T extends Entity> {
    поля и методы для сохранения, получения сущностей
    abstract validate(T entity); // реализуется в контроллерах наследниках
}

2023-08-14 17:55 UTC, denis-shishki commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        UserValidator.validate(user);
Исправил. Получается валидаторы перестали быть статичными.

2023-08-14 17:59 UTC, denis-shishki commented
> Т.к. у обоих контроллеров одинаковая функциональнось по работе с сущностями модели (разница только в валидации), то можно выделить ее в базовый контроллер. Сущности модели тоже имеют общую часть - идентификатор, и можно сделать базовый класс, назвать например Entity. В итоге базовый контроллер мог бы иметь такое определение
> 
> ```
> public abstract class Controller<T extends Entity> {
>     поля и методы для сохранения, получения сущностей
>     abstract validate(T entity); // реализуется в контроллерах наследниках
> } 
> ```
Случайно закрыл диалог про создание базового класса...
Уже начался новый спринт, поэтому пока отложу.

2023-08-14 19:42 UTC, denis-shishki commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        UserValidator.validate(user);
Не, не работает. я все сломал и "откатил" назад. Одной лишь аннотацией не обойтись. У нас спринг 2 версии, может на версиях старше это проще делается. Где-то пишут, что нужно использовать несколько аннотаций и что-то с бинами.

2023-08-14 19:43 UTC, denis-shishki commented
В общем я все вернул как было. Надеюсь у меня будет дальше свободное время, для проработки твоих советов. Спасибо

2023-08-21 18:44 UTC, merged